version: 2
updates:
  # NPM dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "automerge"
    versioning-strategy: "auto"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "⬆️ "
      include: "scope"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "⚡️ " 